services:
  db:
    image: postgres:15
    container_name: haic-postgres
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db-init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: haic-minio
    env_file: .env
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET: ${MINIO_BUCKET}
      MINIO_REGION: ${MINIO_REGION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      LOG_LEVEL: ${LOG_LEVEL}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
      - ./docker/minio-init:/minio-init
    entrypoint: sh
    command: >
      -c '
        mkdir -p /data/humaine &&
        cp -r /minio-init/humaine/* /data/humaine &&
        /usr/bin/minio server /data --console-address ":9001"
      '
  migrations:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.backend
    command: alembic upgrade head
    env_file: .env
    environment:
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET: ${MINIO_BUCKET}
      MINIO_REGION: ${MINIO_REGION}
      LOG_LEVEL: ${LOG_LEVEL}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
    depends_on:
      - db

  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.backend
    container_name: haic-backend
    env_file: .env
    environment:
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET: ${MINIO_BUCKET}
      MINIO_REGION: ${MINIO_REGION}
      LOG_LEVEL: ${LOG_LEVEL}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - minio

  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.frontend
    container_name: haic-frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
  
  # Run only for the integration with HAIC
  node-red:
    image: nodered/node-red
    container_name: haic-node-red
    ports:
      - "1880:1880"
    volumes:
      - ./node-red:/data
    environment:
      TZ: "Europe/Athens"
    depends_on:
      - backend

volumes:
  postgres_data:
  minio_data:
