task_name: My Environment
task_description: v1
task_parameters:
  environment: ct_scan
  env_params: {}
  dt: 0.1
  rt_max: 5.0
  baseline_s: null
agent_definitions:
- id: hu1
  name: Radiologist
  type: human
  profile: default
- id: ai1
  name: AI Assistant
  type: ai
  profile: gpt
profile_definitions:
- id: default
  type: human
  parameters: {}
- id: gpt
  type: ai
  parameters: {}
