task:
  name: Medical Environment (ct_demo)
  description: Environment version v1
  parameters:
    environment: ct_scan
    env_params: {}
    dt: 0.1
    rt_max: 5.0
    domain: medical
    metrics:
      rt_max: 5
      baseline_s: 2
agents:
- name: A1
  modality: policy
  capabilities: []
  runtime_params: {}
  type: human
  profile: Radiologist
- name: A2
  modality: policy
  capabilities: []
  runtime_params: {}
  type: ai
  profile: Agent
profiles: []
