apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: benchmarking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
      - name: frontend
        image: ghcr.io/gfragi/haic-frontend:rollback
        ports:
        - containerPort: 80
        env:
        - name: BACKEND_URL
          valueFrom:
            secretKeyRef:
              name: frontend-secret
              key: VUE_APP_API_BASE_URL
        - name: KEYCLOAK_URL
          valueFrom:
            secretKeyRef:
              name: frontend-secret
              key: VUE_APP_KEYCLOAK_URL
        - name: KEYCLOAK_REALM
          valueFrom:
            secretKeyRef:
              name: frontend-secret
              key: VUE_APP_KEYCLOAK_REALM
        - name: KEYCLOAK_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: frontend-secret
              key: VUE_APP_KEYCLOAK_CLIENT_ID
