apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: benchmarking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
      - name: frontend
        image: ghcr.io/gfragi/haic-frontend:latest
        ports:
        - containerPort: 80