apiVersion: v1
kind: Secret
metadata:
  name: ghcr-pull-secret
  namespace: benchmarking
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiZ2ZyYWdpIiwicGFzc3dvcmQiOiJnaHBfUW1qb1hlRkxjNjIxanBKVXBwaHJVV3p5TnJFcE9SM3RWZHZHIiwiYXV0aCI6IloyWnlZV2RwT21kb2NGOVJiV3B2V0dWR1RHTTJNakZxY0VwVmNIQm9jbFZYZW5sT2NrVndUMUl6ZEZaa2RrYz0ifX19

